### ISSUE TITLE
Adding Wheel Build Steps

### ISSUE THREAD

**Issue by jmwright** [CadQuery/vtk-build-system#1]
@fpq473 If you look at the [latest build](https://github.com/CadQuery/vtk-build-system/actions/runs/3989843235), you'll see that VTK was installed to `/home/runner/work/vtk-build-system/install/` after a build. I may not have all the cmake options set correctly yet, but it's a starting point. Is that enough to go on to package the wheel so we can test it?

**Comment by fpq473** [comment]
After poking around, I think that's tough for me.  I really need a working wheel as a starting point (a wheel that works inside the conda env that runs the OCP wheel build).  It seems like running `python setup.py bdist_wheel` at the right time/place is needed, followed by `auditwheel`.

I think this is where the VTK pipeline makes the wheel:

https://gitlab.kitware.com/vtk/vtk/-/blob/925a2929c1d38a857596fac7e37ef52d6f245e16/.gitlab/os-linux.yml#L421

**Comment by jmwright** [comment]
Here is the first build where I got the wheel to upload correctly. https://github.com/CadQuery/vtk-build-system/actions/runs/4010650754

**Comment by fpq473** [comment]
I was able to manually run the `ocp-build-system` workflow using this wheel to produce a seemingly working manylinux\_2\_31 wheel: import cadquery, make a solid, convert it to vtk polydata.  Is there a recommended way of running cadquery tests?

Before we declare victory, two things to note:

(1) The vtk wheel built here wasn't a manylinux wheel, yet the ocp build still worked.  This was surprising.

(2) The manylinux wheel from PyPI contains many more files than the wheel built here.  So our wheel might not be a fully-featured wheel.  Pasting just a fraction of the diff in filenames, we have:
```diff
@@ -8,6 +7,9 @@ vtkmodules/gtk/GtkVTKRenderWindowInteractor.py
 vtkmodules/gtk/GtkVTKRenderWindow.py
 vtkmodules/gtk/__init__.py
 vtkmodules/__init__.py
+vtkmodules/libvtkAcceleratorsVTKmCore-9.2.so
+vtkmodules/libvtkAcceleratorsVTKmDataModel-9.2.so
+vtkmodules/libvtkAcceleratorsVTKmFilters-9.2.so
 vtkmodules/libvtkcgns-9.2.so
 vtkmodules/libvtkChartsCore-9.2.so
 vtkmodules/libvtkCommonColor-9.2.so
@@ -38,7 +40,9 @@ vtkmodules/libvtkFiltersHyperTree-9.2.so
 vtkmodules/libvtkFiltersImaging-9.2.so
 vtkmodules/libvtkFiltersModeling-9.2.so
 vtkmodules/libvtkFiltersParallel-9.2.so
+vtkmodules/libvtkFiltersParallelDIY2-9.2.so
 vtkmodules/libvtkFiltersParallelImaging-9.2.so
+vtkmodules/libvtkFiltersParallelStatistics-9.2.so
 vtkmodules/libvtkFiltersPoints-9.2.so
 vtkmodules/libvtkFiltersProgrammable-9.2.so
 vtkmodules/libvtkFiltersPython-9.2.so
@@ -54,6 +58,7 @@ vtkmodules/libvtkfreetype-9.2.so
 vtkmodules/libvtkGeovisCore-9.2.so
 vtkmodules/libvtkgl2ps-9.2.so
 vtkmodules/libvtkglew-9.2.so
+vtkmodules/libvtkh5part-9.2.so
 vtkmodules/libvtkhdf5-9.2.so
 vtkmodules/libvtkhdf5_hl-9.2.so
 vtkmodules/libvtkImagingColor-9.2.so
@@ -63,6 +68,7 @@ vtkmodules/libvtkImagingGeneral-9.2.so
 vtkmodules/libvtkImagingHybrid-9.2.so
 vtkmodules/libvtkImagingMath-9.2.so
 vtkmodules/libvtkImagingMorphological-9.2.so
+vtkmodules/libvtkImagingOpenGL2-9.2.so
 vtkmodules/libvtkImagingSources-9.2.so
 vtkmodules/libvtkImagingStatistics-9.2.so
 vtkmodules/libvtkImagingStencil-9.2.so
@@ -84,7 +90,10 @@ vtkmodules/libvtkIOExodus-9.2.so
 vtkmodules/libvtkIOExport-9.2.so
 vtkmodules/libvtkIOExportGL2PS-9.2.so
 vtkmodules/libvtkIOExportPDF-9.2.so
+vtkmodules/libvtkIOGeoJSON-9.2.so
 vtkmodules/libvtkIOGeometry-9.2.so
+vtkmodules/libvtkIOH5part-9.2.so
+vtkmodules/libvtkIOH5Rage-9.2.so
 vtkmodules/libvtkIOHDF-9.2.so
 vtkmodules/libvtkIOImage-9.2.so
 vtkmodules/libvtkIOImport-9.2.so
@@ -97,15 +106,22 @@ vtkmodules/libvtkIOMotionFX-9.2.so
 vtkmodules/libvtkIOMovie-9.2.so
 vtkmodules/libvtkIONetCDF-9.2.so
 vtkmodules/libvtkIOOggTheora-9.2.so
+vtkmodules/libvtkIOOMF-9.2.so
 vtkmodules/libvtkIOParallel-9.2.so
+vtkmodules/libvtkIOParallelExodus-9.2.so
+vtkmodules/libvtkIOParallelLSDyna-9.2.so
 vtkmodules/libvtkIOParallelXML-9.2.so
+vtkmodules/libvtkIOPIO-9.2.so
 vtkmodules/libvtkIOPLY-9.2.so
 vtkmodules/libvtkIOSegY-9.2.so
 vtkmodules/libvtkIOSQL-9.2.so
 vtkmodules/libvtkioss-9.2.so
 vtkmodules/libvtkIOTecplotTable-9.2.so
+vtkmodules/libvtkIOTRUCHAS-9.2.so
 vtkmodules/libvtkIOVeraOut-9.2.so
 vtkmodules/libvtkIOVideo-9.2.so
+vtkmodules/libvtkIOVPIC-9.2.so
+vtkmodules/libvtkIOXdmf2-9.2.so
 vtkmodules/libvtkIOXML-9.2.so
 vtkmodules/libvtkIOXMLParser-9.2.so
 vtkmodules/libvtkjpeg-9.2.so
@@ -117,7 +133,28 @@ vtkmodules/libvtklibxml2-9.2.so
 vtkmodules/libvtkloguru-9.2.so
 vtkmodules/libvtklz4-9.2.so
 vtkmodules/libvtklzma-9.2.so
+vtkmodules/libvtkm_cont-9.2.so
+vtkmodules/libvtkm_cont_testing-9.2.so
+vtkmodules/libvtkmdiympi_nompi.so
 vtkmodules/libvtkmetaio-9.2.so
```

So the worry is that I'm testing against a defective wheel (but good enough for CQ?).

**Comment by jmwright** [comment]
> Is there a recommended way of running cadquery tests?

Install pytest into your Python environment and then run `pytest` in the root of the cloned repo.

> The vtk wheel built here wasn't a manylinux wheel, yet the ocp build still worked. 

I ended up learning that VTK has an official cmake option to build a wheel, so I used that. It must target only the specific platform it was built on. I would like to build on Ubuntu 18.04 to cover earlier glibc versions too, but GitHub does this brownout thing with 18.04 runners to try to force people to upgrade.

> The manylinux wheel from PyPI contains many more files than the wheel built here.

That's probably because they enabled everything when they built it. I can turn on more features via cmake options if we need them.

**Comment by jmwright** [comment]
Adding to my comment above, here are the options shown by ccmake when configuring VTK 9.2.5 locally.

![Screenshot from 2023-01-26 06-06-51](https://user-images.githubusercontent.com/1015439/214821896-56f96e4a-2381-4973-b80d-d2a820bb0f64.png)

![Screenshot from 2023-01-26 06-07-23](https://user-images.githubusercontent.com/1015439/214821959-ef658118-0ed2-4c0d-a7b5-b7756f63c9df.png)

**Comment by fpq473** [comment]
Thanks.  So 494 tests and 1 failed (below).  Probably unrelated to our work here.

If we can make these build artifacts available to the ocp-build-system workflow, then I think we should be able to build cadquery-ocp wheels.

```
self = <tests.test_cadquery.TestCadQuery testMethod=test_project>
                                                                                                                                                                    
    def test_project(self):                                                       
                                                                                                                                                                    
        # project a single letter                                                 
        t = Compound.makeText("T", 5, 0).Faces()[0]          
        f = Workplane("XZ", origin=(0, 0, -7)).sphere(6).faces("not %PLANE").val()                                                                                  
                                                                                                                                                                    
        res = t.project(f, (0, 0, 1))                                             
                                                                                                                                                                    
        assert res.isValid()                                                                                                                                        
>       assert len(res.Edges()) == len(t.Edges())                                                                                                                   
E       assert 9 == 8
```

**Comment by jmwright** [comment]
> If we can make these build artifacts available to the ocp-build-system workflow, then I think we should be able to build cadquery-ocp wheels.

So you're thinking that we don't publish our own cadquery-vtk wheel? How would the wheel generated here be integrated into the OCP wheel build? I'm not sure I follow.

**Comment by fpq473** [comment]
I hadn't landed on any particular way yet.  Publishing the wheel (I assume you mean to PyPI) works but seems circuitous if the wheels are simply bundled into the cadquery-ocp wheel.  (With hindsight, I see you already proposed this in https://github.com/CadQuery/ocp-build-system/issues/10#issuecomment-1399317615, which I hadn't fully grasped.)

Drawing inspiration from ocp-build-system, it seems like the wheel-publishing workflow downloads wheels from the wheel-building workflow.  So if we move `build-vtk.yml` into ocp-build-system, then the vtk wheel can be downloaded by `build-wheel.yml`?

**Comment by jmwright** [comment]
> then the vtk wheel can be downloaded by build-wheel.yml?

That should work. It would be similar to how the OCP publish action in ocp-build-system pulls the artifacts from the latest OCP wheel build. However, I'm not familiar enough with wheels to understand how the VTK wheel will be included in the OCP wheel as it's being built. If you're comfortable with that part I can move the `build-vtk.yml` file over to ocp-build-system and work on getting the artifacts downloaded into the main build.

**Comment by fpq473** [comment]
Yes, I'm comfortable with that part, so let's move `build-vtk.yml` over and trigger it for all relevant python versions.

I think I know how to download, so you can hold off on that if you'd like.

**Comment by jmwright** [comment]
@fpq473 Have a look [here](https://github.com/CadQuery/ocp-build-system/actions/runs/4024157751)

**Comment by fpq473** [comment]
@jmwright Looks like every run produced a 3.8 wheel.  Output from this [download step](https://github.com/CadQuery/ocp-build-system/blob/045df4db94e947da1328c1ca246b6192b12f39b5/.github/workflows/build-wheel.yml#L24-L29):

```
2023-01-27T17:24:59.9327878Z ==> Repository: CadQuery/ocp-build-system
2023-01-27T17:24:59.9328311Z ==> Artifact name: 
2023-01-27T17:24:59.9328635Z ==> Local path: /tmp/vtk-wheels
2023-01-27T17:24:59.9328931Z ==> Workflow name: build-vtk.yml
2023-01-27T17:24:59.9329309Z ==> Workflow conclusion: success
2023-01-27T17:25:00.1405379Z ==> (found) Run ID: 4024157751
2023-01-27T17:25:00.1406076Z ==> (found) Run date: 2023-01-27T11:44:53Z
2023-01-27T17:25:00.2975824Z ==> Artifact: 529905618
2023-01-27T17:25:00.2984532Z ==> Downloading: cadquery-vtk-ubuntu-20.04-cp3.10.zip (388.88 MB)
2023-01-27T17:25:35.4101853Z ##[group]==> Extracting: cadquery-vtk-ubuntu-20.04-cp3.10.zip
2023-01-27T17:25:35.4102710Z   inflating: /tmp/vtk-wheels/cadquery-vtk-ubuntu-20.04-cp3.10/vtk-9.2.5.dev0-cp38-cp38-linux_x86_64.whl
2023-01-27T17:25:37.1274294Z ##[endgroup]
2023-01-27T17:25:37.1275267Z ==> Artifact: 529905619
2023-01-27T17:25:37.1286519Z ==> Downloading: cadquery-vtk-ubuntu-20.04-cp3.11.zip (388.88 MB)
2023-01-27T17:26:12.4773870Z ##[group]==> Extracting: cadquery-vtk-ubuntu-20.04-cp3.11.zip
2023-01-27T17:26:12.4777919Z   inflating: /tmp/vtk-wheels/cadquery-vtk-ubuntu-20.04-cp3.11/vtk-9.2.5.dev0-cp38-cp38-linux_x86_64.whl
2023-01-27T17:26:13.9954287Z ##[endgroup]
2023-01-27T17:26:13.9967195Z ==> Artifact: 529905620
2023-01-27T17:26:13.9968228Z ==> Downloading: cadquery-vtk-ubuntu-20.04-cp3.8.zip (388.88 MB)
2023-01-27T17:26:50.7603054Z ##[group]==> Extracting: cadquery-vtk-ubuntu-20.04-cp3.8.zip
2023-01-27T17:26:50.7609572Z   inflating: /tmp/vtk-wheels/cadquery-vtk-ubuntu-20.04-cp3.8/vtk-9.2.5.dev0-cp38-cp38-linux_x86_64.whl
2023-01-27T17:26:52.2702265Z ##[endgroup]
2023-01-27T17:26:52.2702955Z ==> Artifact: 529905621
2023-01-27T17:26:52.2703667Z ==> Downloading: cadquery-vtk-ubuntu-20.04-cp3.9.zip (388.88 MB)
2023-01-27T17:27:27.3670331Z ##[group]==> Extracting: cadquery-vtk-ubuntu-20.04-cp3.9.zip
2023-01-27T17:27:27.3676796Z   inflating: /tmp/vtk-wheels/cadquery-vtk-ubuntu-20.04-cp3.9/vtk-9.2.5.dev0-cp38-cp38-linux_x86_64.whl
```

**Comment by jmwright** [comment]
@fpq473 Here's a [first attempt](https://github.com/CadQuery/ocp-build-system/actions/runs/4028202466) at getting each matrix run to use a different Python version. It may take me a few tries to get it working correctly. I'm not sure if I will have to change the Python paths for cmake or not.

**Comment by fpq473** [comment]
Let's consolidate the discussion in https://github.com/CadQuery/ocp-build-system/issues/10

**Comment by jmwright** [comment]
@fpq473 Do you agree that I can delete this repo? It was useful for getting us to the final result, but it's not doing anything now other than cluttering things up.

**Comment by fpq473** [comment]
Yes, let's.  Thanks for wrapping things up in the other repo.
